<a href="https://colab.research.google.com/github/Luv-Gupta13/BCS_Luv_Gupta/blob/main/Assignment1_Luv-Gupta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np


In [4]:
# Loading the dataset
file_path = '/content/sample_data/california_housing_train.csv'
df = pd.read_csv(file_path)
# Display the first 5 and last 10 rows
df.head(5), df.tail(10)



(   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 0    -114.31     34.19                15.0       5612.0          1283.0   
 1    -114.47     34.40                19.0       7650.0          1901.0   
 2    -114.56     33.69                17.0        720.0           174.0   
 3    -114.57     33.64                14.0       1501.0           337.0   
 4    -114.57     33.57                20.0       1454.0           326.0   
 
    population  households  median_income  median_house_value  
 0      1015.0       472.0         1.4936             66900.0  
 1      1129.0       463.0         1.8200             80100.0  
 2       333.0       117.0         1.6509             85700.0  
 3       515.0       226.0         3.1917             73400.0  
 4       624.0       262.0         1.9250             65500.0  ,
        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 16990    -124.22     41.73                28.0       3003.0           699.0 

In [5]:
df.describe()
#Getting the statistical summary
uniquerooms = df['total_bedrooms'].unique()
disrooms = len(uniquerooms)
#Finding unique values in total bedrooms
uniquerooms, disrooms


(array([1283., 1901.,  174., ..., 1637., 1308.,  936.]), 1848)

In [6]:
df['total_bedrooms_per_total_rooms'] = df['total_bedrooms'] / df['total_rooms']
#Adding the New coloumn and calculating mean and std deviation
meanbedrooms = df['total_bedrooms_per_total_rooms'].mean()
stdbedrooms = df['total_bedrooms_per_total_rooms'].std()
meanbedrooms, stdbedrooms


(0.21275998821034803, 0.057823008903161756)

In [7]:
income = df[df['median_income'] > 5]
value = df[(df['total_rooms'] > 10000) & (df['median_house_value'] < 150000)]
#Filter median income > 5 and Total rooms >10k and Median house value < 150k
income.head(), value.head()


(     longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 32     -115.39     32.76                16.0       1136.0           196.0   
 69     -115.55     32.98                33.0       2266.0           365.0   
 92     -115.57     32.78                20.0       1534.0           235.0   
 98     -115.58     32.78                 5.0       2494.0           414.0   
 100    -115.59     32.79                 8.0       2183.0           307.0   
 
      population  households  median_income  median_house_value  \
 32        481.0       185.0         6.2558            146300.0   
 69        952.0       360.0         5.4349            143000.0   
 92        871.0       222.0         6.2715             97200.0   
 98       1416.0       421.0         5.7843            110100.0   
 100      1000.0       287.0         6.3814            159900.0   
 
      total_bedrooms_per_total_rooms  
 32                         0.172535  
 69                         0.161077  
 92      

In [8]:
#Saving to new csv file
new_file_path = '/content/sample_data/california_housing_modified.csv'
df.to_csv(new_file_path, index=False)


In [10]:
array_1_20 = np.arange(1, 21)
#creating an array of numbers from 1 to 20
array_1_20[array_1_20 % 2 == 0]#slicing

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
RandomArray = np.random.randint(10, 100, size=(5, 4))
#creating random array
RandomArray[:3, :2]#3X2 subbarray

array([[78, 33],
       [97, 58],
       [87, 81]])

In [12]:
ReshapedArray = array_1_20.reshape(4, 5)
FlattenedArray = ReshapedArray.flatten()
#reshapping and flatenning the array
FlattenedArray


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
RandomMultArray = np.random.randint(1, 100, size=(4, 5))
MatrixMultiply = np.dot(RandomArray,RandomMultArray)
MatrixMultiply #matrix multiply

array([[23793, 18961, 16838, 15668, 11939],
       [19894, 15955, 18715,  9218,  9841],
       [19800, 17795, 17851, 10948,  9871],
       [18692, 17081, 14405, 12735,  8154],
       [15214, 10162,  9316, 10394,  5348]])

In [14]:
RandomArr = np.random.randint(0, 100, size=50)#random array creation
RandomArr[RandomArr > 50]#values > 50
indices = [2, 12, 17, 29, 39]#fancy indexing
RandomArr[indices]

array([50, 17, 48, 65, 21])

In [18]:
mean = RandomArray.mean(axis=0)
max = RandomArray.max(axis=0)
sum = RandomArray.sum(axis=0)
mask = RandomArray > mean
#calculating mean, max, sum and creating a mask
mean, max, sum , RandomArray[mask]

(array([64.2, 52.4, 50.6, 59. ]),
 array([97, 81, 74, 97]),
 array([321, 262, 253, 295]),
 array([78, 66, 97, 97, 58, 56, 87, 81, 80, 70, 74, 82]))

In [24]:
# Fibonacci sequence
x, y = 0, 1
while x <= 100:
    print(y, end=" ")
    x, y = y, x + y

1 1 2 3 5 8 13 21 34 55 89 144 

In [25]:
#Fizzbuzz problem
for i in range(1, 51):
    if i % 3 == 0 and i % 5 == 0: #no. divisible by both 3 and 5
        print("FizzBuzz")
    elif i % 3 == 0:: # no. divisible only by 3
        print("Fizz")
    elif i % 5 == 0: # no. divisible only by 5
        print("Buzz")
    else:
        print(i)


1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


In [39]:
#division by zero error
try:
    result = 10 / 0
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")



Error: Division by zero is not allowed.


In [38]:

def Median(numbers):
    numbers.sort()
    n = len(numbers)
    if n % 2 == 0:
        return ((numbers[n // 2 - 1])+numbers[n // 2])/ 2
    else:
        return numbers[n // 2]

Input = input("Enter numbers")
numbers = Input.split()
numbers = [float(num) for num in numbers]
median = Median(numbers)
print("Median:", median)



Enter numbers1 2 3 4
Median: 2.5
